Repository wallace0003/projeto-5, pull requests merged in 2024-05, with the labels that each got.

#20 Telefone deve ser único
  contato.c
Labels: enhancement

#25 Numero int
  contato.c
  contato.h
Labels: bug

#26 Segunda agenda
  contato.c
  contato.h
  main.c
Labels: enhancement

#31 função de e-mail alterada para verificar @ e .
  contato.c
Labels: bug

#32 bug de email de digitar apenas o . corrigido
  contato.c
Labels: bug

#33 Atualização da documentação
  README.md
Labels: documentation
