Repository wallace0003/projeto-5, pull requests merged in 2024-04, with the labels that each got.

#3 Função para adicionar contato foi um sucesso
  contato.c
  contato.h
  main.c
Labels: enhancement

#5 Listar contato
  contato.c
  contato.h
  main.c
Labels: enhancement

#7 função de deletar contatos foi um sucesso
  contato.c
  contato.h
  main.c
Labels: enhancement

#9 Função Salvar em binario
  contato.c
  contato.h
  main.c
Labels: enhancement

#13 Carregando binario
  contato.c
  main.c
Labels: enhancement

#15 possíveis bugs nos campos nome e sobrenome foi resolvido
  contato.c
  contato.h
Labels: bug

#16 Realizado a documentação do projeto 3
  README.md
Labels: documentation

#17 Correcao da function contem_apenas_letras
  contato.c
Labels: bug
